Update demo.yml

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -1,45 +1,46 @@
+
 name: Prisma Cloud Compute Image Scan
 
 on: [push, pull_request]
 
-permissions:
-  contents: read
-
 env:
-  PRISMA_CLOUD_URL: "https://api3.prismacloud.io"
-  DOCKER_IMAGE: "ghcr.io/${{ github.repository }}/apache-app:latest"
+  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
 
 jobs:
+  # Jobs are ran independently from each other, so build and scan needs to be in a single job.
   build-and-scan:
     name: Build and scan image
     runs-on: ubuntu-latest
+
     steps:
       - name: Check out the repository
         uses: actions/checkout@v2
-
-      - name: Remove conflicting containerd package
-        run: |
-          sudo apt-get remove -y containerd || true
-
-      - name: Install Docker
-        run: |
-          curl -fsSL https://get.docker.com | sudo sh
-          sudo systemctl start docker
-          sudo systemctl enable docker
-
-      - name: Build Docker Image
-        run: |
-          docker build -t ${{ env.DOCKER_IMAGE }} .
-          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}
+        # Defaults are sufficient generally
+        # https://github.com/actions/checkout#usage
 
       - name: Download twistcli from the Prisma Cloud Compute Console
         run: |
-          curl --insecure --user ${{ secrets.TL_USER }}:${{ secrets.TL_PASS }} --output ./twistcli https://${{ secrets.PATH_TO_CONSOLE }}/api/v1/util/twistcli
+          curl --insecure --user ${{ secrets.PCC_USER }}:${{ secrets.PCC_PASS }} --output ./twistcli ${{ secrets.PCC_CONSOLE_URL }}/api/v1/util/twistcli
           chmod a+x ./twistcli
-
-      - name: Scan the image
+      - name: Build the image
         run: |
-          ./twistcli images scan --address https://${{ secrets.PATH_TO_CONSOLE }} \
-                                 --user ${{ secrets.TL_USER }} \
-                                 --password ${{ secrets.TL_PASS }} \
-                                 --details ${{ env.DOCKER_IMAGE }}
+          cat <<EOF | tee ${{ github.workspace }}/Dockerfile
+          FROM nginx:1.21
+          EXPOSE 80
+          CMD ["nginx", "-g", "daemon off;"]
+          EOF
+          docker build -t $IMAGE_NAME .
+      - name: Scan the image
+        run: ./twistcli images scan --address ${{ secrets.PCC_CONSOLE_URL }} --user ${{ secrets.PCC_USER }} --password ${{ secrets.PCC_PASS }} --details $IMAGE_NAME
+      
+      - name: Scan the dynamic image analysis
+        run: sudo ./twistcli sandbox --address ${{ secrets.PCC_CONSOLE_URL }} --token ${{ secrets.PCC_API_TOKEN }} --user ${{ secrets.PCC_USER }} --password ${{ secrets.PCC_PASS }} --analysis-duration 2m --exit-on-error  $IMAGE_NAME
+
+      - name: Check for specific string
+        run: |
+          if grep -q "PASS" ./path/to/${{ github.workspace }} ; then
+            echo "Specific string found!"
+            exit 1
+          else
+            echo "Specific string not found."
+          fi
